defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: budpage
  password: budpage
  host: localhost
  port: 5432

  # Schema search path. The server defaults to $user,public
  #schema_search_path: myapp,sharedapp,public

  # Minimum log levels, in increasing order:
  #   debug5, debug4, debug3, debug2, debug1,
  #   log, notice, warning, error, fatal, and panic
  # The server defaults to notice.
  #min_messages: warning

development:
  <<: *defaults
  database: budpage_development

test:
  <<: *defaults
  database: budpage_test

production:
  <<: *defaults
  database: budpage_production